// <auto-generated />
using Exvo.BookingService.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Exvo.BookingService.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260923183000_AllowGeneralAdmissionBookingItems")]
    partial class AllowGeneralAdmissionBookingItems
    {
    }
}
