// <auto-generated />
using Exvo.BookingService.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Exvo.BookingService.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260924221500_AddBookingAttendeeEmail")]
    partial class AddBookingAttendeeEmail
    {
    }
}
